[CREDENCIAIS_GOOGLE]
type = "service_account"
project_id = "plexiform-pilot-429019-a0"
private_key_id = "c95620223e32324a988bc521c9339cff4554e492"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDaO43aaCAjfRt1
26Tmjm0KkY8kxo2AsCDsIbuNuwNeQc5t0vVX3r8oN8wzYmcH4RMTOsaKGl4v1Loy
LiddYwjsp2cTTuTh3/3HlJ56MMATcF53abJ07iC2ttSY4l0CbCqE7rCc0t1Eh1tN
ALkAcO3vJYr4i/wilUa3ZgFpiY77tDfyTbdCprXv6wll68AfOb1AH4OctOhKMDvE
gx7Yat200fQUamLQaGL6gjkIzGLv5M8Z7MJQSIH1KIyna7LC36y0EYV8h7ZIbZph
eqL96VpjItj1wxeC1rltmGv/lbBBO/2HSRDW8wX8ovVGeaQW2yuKQ+ODfaPN+cIz
jPLs18J1AgMBAAECggEAap5u8vYtQXlleaLKQTPzVRcBUsvIpUcnhoYCfj+QaTQI
WQKYiAoU5V7BXpdkU+akLaBpEF7Khl7Naye+ZrM0UH6G7tl8HFiVQbU76eG4babY
GEok/Fi81dekLV9mZoEXEuQUmEGzBcCFnCzOtcb2kACNEVo+4FyC9KYa6YdhulmO
ceQJKpgHQ35I+ql5oQSEXh2srRLla2QJAoRk4NmEDMJK6TtEJZb39uzlzrGVGGL2
q0wA7EcI8oFG6S0HeMZjmIfcqtAvSLa4YSiaLOKwPeNdX6Y3raOvQxzg5qhSbYJ9
X7MuymhE+NgBOR+DXeWOdCce7LPHhQ+xK+BFb4E03wKBgQDzCpUIAOeUBQ9wtIOI
3mD9ZQNqdfxgzRm0WXqFRkq+5BLWbVgri3oU/TS++Im2QtGm/+ODZ2tARDxVcIjl
LvVGvtxeC923HezjKWhTLBmwHSeCXQiO89+KRnkSeH37/cf9QL3geWiBOeoh0FGM
bQT2u0tj5ESRdoBqOFvoaV4Q1wKBgQDl3lfO4rAhW4lIxYkrotY8Xenu02NvO3t3
qKaW4eVtVv6DiZtVZqeKhv39KLQEyAjm8f5vKdneZ3is1rncjPsR1cpGNoC7WJaO
7mkG6Oo4g7edhgK/wnsazmN9fp+rOuUNenklvikm377Raejotx0aPPhzLr0DesSV
EsdEia7BkwKBgFTWo9FIZ44u+gXQrX2witDJWxjlmLS9w7RF69PsBpl+CelaAAYr
SPFctfXX0lKSHpcaCfRLvI+RgjIc91xxOON6KniV0c5jHtbpFGa8JTdp5enGyf8E
uEqPcSH2d5voKdCIsf9Swh0h903YZy8Ku0nZdWaoPxs773WkuMh3R4O/AoGAW/rM
SAyNTcvC80uXx84wy5cItHgBodC7ZvYlMtrRYx8cWKYHcfTRtayulU5kOkWQyliq
5vBoLYZZ009Yr9f53vkdJ1tHx697D1Z20D0C+/o4zt+A2hqICAHt7Zltaqb2YJ5R
O7kL3nJJeKJYgEZFbupWwEBDgdDuOHh7JAGz2+ECgYAY0DXxe1OvzGj1NjYgeXNS
MGIuA9StXhiksl/M9Yse1Inn1/K1bh7SQB4+pgnNS6OwB5JpbYddVMJA+rMKyISK
/BYHC+jjgyyMHIpogozNDzkyI0PTup45L0GpY/8O51YKBHJ9NgnB66lYn+nVQHTv
dZrXDasJFJjOX8r64lMCHg==
-----END PRIVATE KEY-----
"""

client_email = "fuji-reservas@plexiform-pilot-429019-a0.iam.gserviceaccount.com"
client_id = "104620015933808824990"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/fuji-reservas%40plexiform-pilot-429019-a0.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[email]
origem = "financeirofujilounge@gmail.com"
senha_app = "noic lszt cxti yapc"